version: '3'

services:
  app:
    container_name: transfer-api-app
    build:
      context: ./.setup/build
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - transfer-api

  mysql:
    image: mysql:8.0.11
    container_name: transfer-api-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      TZ: "America/Sao_Paulo"
    volumes:
      - .docker-volumes/mysql:/var/lib/mysql
      - ./.setup/build/dev/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - transfer-api

  nginx:
    container_name: transfer-api-nginx
    build: ./.setup/build/dev/nginx/
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./.setup/build/dev/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - transfer-api

  redis:
    image: redis:alpine
    container_name: transfer-api-redis
    networks:
      - transfer-api

networks:
  transfer-api:
    driver: bridge
